apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: $__env{INFLUX_URL}
    jsonData:
      version: Flux
      organization: $__env{INFLUX_ORG}
      defaultBucket: $__env{INFLUX_BUCKET}
      httpMode: POST
    secureJsonData:
      token: $__env{INFLUX_TOKEN}
    isDefault: true
    editable: false
